### ISSUE TITLE
Add to wiki

### ISSUE THREAD

**Issue by sckott** [ropensci/webservices#179]
@leeper we have an older list of to-dos' we can move from https://github.com/ropensci/rOpenSci/wiki/APIs-to-maybe-use

**Comment by leeper** [comment]
Done: https://github.com/ropensci/webservices/wiki/ToDo/_compare/44e25c702f4e962527577b4064eedfdbebcea4b9...d46c47c24378c9e8618a97b9a3fa906369c475c6

**Comment by sckott** [comment]
Awesome, thx :rocket:
