### ISSUE TITLE
webservices wiki focus

### ISSUE THREAD

**Issue by sckott** [ropensci/webservices#193]
@leeper given https://github.com/ropensci/wishlist we should keep the wiki to do list, but state on top that we're focusing on non-science related pkgs, and point people to `wishlist` if their idea applies there

okay @karthik ?

**Comment by karthik** [comment]
:+1:

**Comment by leeper** [comment]
Agreed. And I guess I'd be inclined to add something at `wishlist` to point here if it's a web API wishlist request.

**Comment by sckott** [comment]
@leeper  Right, good point about pointing back here too

**Comment by sckott** [comment]
edited the wiki landing page https://github.com/ropensci/webservices/wiki

**Comment by leeper** [comment]
I'm closing this because it seems like we've pretty much handled it.
