### ISSUE TITLE
Add Radiant to Webframeworks

### ISSUE THREAD

**Issue by vnijs** [ropensci/webservices#206]
I noticed you had Rapporter listed in Webframeworks. If Raportter (which looks very nice btw) is a Webframework then I guess so is Radiant :) Radiant is an (open source) GUI for R that runs in a browser from a server (or a local machine). In addition to various statistical tools it also has coding and rmarkdown features (e.g., run a cluster-analysis and press the book icon on the bottom left of the page to create an rmarkdown report). See the  [video tutorial](https://youtu.be/T_NQPfrWN-g?t=145) I made for my students this past Fall. 

If you are using Radiant on a server you can share the url (include the SSUID) with others so they can see what you are working on (i.e., the url gives access to a users R-session). It is not exactly google-docs but if two users share a session link and hit refresh to 'commit' changes they can work together on an analysis conducted on a server. Joe Cheng at Rstudio helped me out with this feature.

You can also save the state of the app (i.e., analysis settings and data) to a file and share that with others that would like to replicate your analysis or put it on dropbox to work on it later and/or on another device. See this [tutorial](https://youtu.be/ioHopyfD2f0?t=140)

Radiant is on CRAN and github:

https://github.com/vnijs/radiant
http://cran.rstudio.com/web/packages/radiant/index.html

Due to security concerns running user-entered code is currently deactivated when running Radiant on a (shiny) server. If you have any suggestions on how to overcome those concerns I would be very interested.

See also a blog post that will hopefully be on R-bloggers soon: http://vnijs.github.io/blog/2015/04/introducing-radiant.html

**Comment by sckott** [comment]
this sounds good to add here, any objection @leeper  ?

**Comment by leeper** [comment]
Looks good!


Thomas J. Leeper
http://www.thomasleeper.com

On Wed, Apr 15, 2015 at 8:49 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
@vnijs we'll add it in, thanks for the ping

**Comment by vnijs** [comment]
Great! Thanks @sckott
