### ISSUE TITLE
cdcfluview is now on CRAN

### ISSUE THREAD

**Issue by hrbrmstr** [ropensci/webservices#241]
https://cran.rstudio.com/web/packages/cdcfluview/ (not sure if it's kosher for the pkg author to do a PR :-)

**Comment by leeper** [comment]
Totally kosher!

**Comment by hrbrmstr** [comment]
ah. cool. so I forked the repo and looked for `cdcfluview` and it's weirdly not in there though _someone_ (not me :-) did put it in at some point since it's on the official Task View: https://cran.rstudio.com/web/views/WebTechnologies.html

Any guidance for how y'all'd like me to proceed wld be most welcome since I really don't want to mess anything up (I can super-excel at that sometimes).

**Comment by leeper** [comment]
@hrbrmstr Well, we may have decided it was more appropriate for the ["Open Data" Task View](https://github.com/ropensci/opendata), which we forked from this one when it got too long...Indeed, it's listed [there](https://github.com/ropensci/opendata#public-health). The border between these two is a little blurry, but Open Data is strictly about data whereas WebTech is about anything web-related that's not just data. I suspect this package is better on the other Task View, though CRAN hasn't published that one yet...

**Comment by hrbrmstr** [comment]
Cool. Thx. I'll fork & mod the Open Data one (which is a pretty cool idea
for a task view, IMO)
