### ISSUE TITLE
maintainer

### ISSUE THREAD

**Issue by sckott** [ropensci/webservices#245]
@leeper feel free to change yourself to the primary maintainer (and your email address instead of mine) since you do most of the work now :smile:

**Comment by leeper** [comment]
Okay, if you insist. :) You'll have to remind me of the process of sending this to CRAN, though.

**Comment by sckott** [comment]
if you don't want to deal with submitting I can still do that, if you do, you just need an account on r-forge https://r-forge.r-project.org/projects/ctv/ then submit using `svn`  after syncing with latest changes from the rforge ctv repo - I can give more details if you want
