### ISSUE TITLE
updates and releases?

### ISSUE THREAD

**Issue by jennybc** [ropensci/webservices#273]
My eyeballs were just drawn to this task view on [CRAN](https://cran.r-project.org/web/views/WebTechnologies.html) and I was struck by how far behind this version it is.

How often does the official Task View get updated? (I can imagine there is some pain involved with that and you don't undertake it lightly.)

Maybe this repo should tag such versions as releases? Or is there some other CRAN-dictated mechanism for versioning a task view and I'm just not detecting it?

**Comment by sckott** [comment]
Probably dates are the only thing exposed on task views. You do submit the task view via svn, but I don't think they expose those shas, and there's no semantic versioning

**Comment by jennybc** [comment]
So is there currently any way to determine which SHA here corresponds to the task view being displayed on CRAN? If I follow you, the answer is no. But you could still elect to use tags here to note that, right?

**Comment by sckott** [comment]
We could, @leeper is dealing with submissions now though, I think :)

**Comment by leeper** [comment]
In principle, yes I'm in charge of this. Haven't done it yet, though. I
agree tags sound like a good idea, as that's the obvious way to map things.

On Tue, Jan 19, 2016 at 4:53 PM, Scott Chamberlain <notifications@github.com

**Comment by leeper** [comment]
If I understand subversion correctly (no promises there), I appear to have [successfully updated this](https://r-forge.r-project.org/scm/viewvc.php/pkg/inst/ctv/WebTechnologies.ctv?root=ctv&view=log) and mapped it to [a dated release](https://github.com/ropensci/webservices/releases/tag/2016-02-05) here on GitHub.

**Comment by jennybc** [comment]
From what little I understand, it looks good!
