### ISSUE TITLE
yet another Twitter API package

### ISSUE THREAD

**Issue by masalmon** [ropensci/webservices#335]
https://github.com/mkearney/rtweet

**Comment by masalmon** [comment]
Thanks. I had not put the CRAN URL but it's actually on CRAN, sorry: https://cran.r-project.org/web/packages/rtweet/index.html cc @mkearney

**Comment by leeper** [comment]
Oops. Thanks for that.

**Comment by masalmon** [comment]
Well oops from me ;-)
