### ISSUE TITLE
Refocus this task view?

### ISSUE THREAD

**Issue by leeper** [ropensci/webservices#413]
Hey everyone - I think it's time for another discussion about this task view. The current backlog of new packages and the sheer number of packages currently included is telling me one of two things probably needs to happen.

Either (1) someone else should take over or jump on as a co-maintainer of this, or (2) we need to rethink what purpose this serves and whether it should in fact list every new API package being put on CRAN or if either (a) the list should be trimmed down to those that pass some kind of quality metrics, or (b) the list should basically not include any of these packages and instead focus on the core tools (basically first 2/3 of the task view).

We've already moved "open data" packages to [the other task view](https://github.com/ropensci/opendata/) as a way to keep things minimal but that is facing the same issue of *too many packages meets too little maintainer time.*

(Aside: I know there's a discussion at useR! about finding packages so maybe we can consider some of that feedback here.)

**Comment by sckott** [comment]
I think doing some kind of quality metric would be great but pretty difficult, and it's clear whoever is maintaining is not going to have much time to do such a thing. 

I like the idea of focusing the task view on the core tools. Then the long list of API wrappers and such could go somewhere else. That somewhere else could be a task view like repository, but not sent to CRAN. So it'd still be on the web and findable.

**Comment by petermeissner** [comment]
Why should those API-bindig packages not be in their own task view? Is publishing stuff as CRAN-Task-View especially time demanding?
