### ISSUE TITLE
License of this repository

### ISSUE THREAD

**Issue by nuest** [ropensci/webservices#429]
I'm thinking about starting a new task view and am not really keen on editing the `.ctv` file by hand. I guess it's no big deal but I would like to ask anyway: _May I build upon the very useful scripts and tools you have in this repo?_
It would be great if you could add a `LICENSE` file!

**Comment by leeper** [comment]
Good question. @sckott do we have a license on the build scripts? The ctv itself is GPL, I suppose.

**Comment by sckott** [comment]
not yet. why is the ctv GPL?  

could we just stick a MIT license - or if there is some GPL here already maybe we need to go with that

**Comment by leeper** [comment]
I was thinking ctv was GPL because it ends up in the ctv package (which is GPL). But if it originates as MIT, that shouldn't be a problem I don't think. Let's go with MIT!

**Comment by sckott** [comment]
sounds goo

**Comment by nuest** [comment]
Thanks for clarifying this - I've started working on my own CTV now using your functions: https://github.com/o2r-project/ctv-computational-environments
