### ISSUE TITLE
sos4R

### ISSUE THREAD

**Issue by nuest** [ropensci/webservices#430]
[sos4R](https://github.com/52North/sos4R) is

> an R client for Sensor Observation Services (SOS) as specified by the Open Geospatial Consortium (OGC). t allows users to retrieve metadata from SOS web services and to interactively create requests for near real-time observation data based on the available sensors, phenomena, observations et cetera using thematic, temporal and spatial filtering.

_Would you see it fitting the "Other Web Services" section?_

On CRAN: https://cran.r-project.org/package=sos4R

**Comment by sckott** [comment]
will do

**Comment by sckott** [comment]
archived on cran

**Comment by nuest** [comment]
Back on CRAN now, just missing Windows binaries: https://cran.r-project.org/package=sos4R

@sckott

**Comment by sckott** [comment]
okay, where do you think it belongs in the task view?
