### ISSUE TITLE
Contributing not via github?

### ISSUE THREAD

**Issue by hfrick** [ropensci/webservices#445]
The sentence `If you can't contribute on GitHub, send Scott an email.` from the [webtech.md](https://github.com/ropensci/webservices/blob/master/webtech.md) file reads `If you can't contribute on GitHub, . ` on the [Task View site](https://cran.r-project.org/web/views/WebTechnologies.html).

**Comment by sckott** [comment]
thanks @hfrick ! sorry about the delay, forgot to make sure i was watching this repo. will fix

**Comment by hfrick** [comment]
no worries :)

**Comment by sckott** [comment]
right, looks fine locally, it's just been screwed up on the task views site
