### ISSUE TITLE
CRAN task view doesn't match what's here

### ISSUE THREAD

**Issue by nealrichardson** [ropensci/webservices#446]
I'd expect that https://cran.r-project.org/web/views/WebTechnologies.html would be showing https://github.com/ropensci/webservices/blob/master/WebTechnologies.html, but they're quite a bit different. The CRAN page has a newer date (2018-05-22 vs. 2018-02-14), and among other content differences, it doesn't include the changes I submitted back in September (https://github.com/ropensci/webservices/pull/425/files), nor the most recent set of additions from February (https://github.com/ropensci/webservices/commit/9a029c381476bf65c89cba88ef1045748f001a52). 

Perhaps I misunderstand how this task view works, or maybe this repository is no longer the source of truth?

Happy to help if I can be of service.

**Comment by sckott** [comment]
thanks for the note. will look into it. I have been meaning to submit a new version for a while now but haven't got around to it. It's surprising to see a recent date on the cran version

@leeper did you happen to submit a new version of this taskview  to cran - looks like the date is 2018-07-04 . I definitely did not submit it.

**Comment by leeper** [comment]
I did not

**Comment by sckott** [comment]
i had never looked at the logs before. Turns out they've (mostly Achim) have been maaking changes all along. fun hugh?

**Comment by leeper** [comment]
Huh. Weird.

**Comment by sckott** [comment]
AFAICT all your changes in https://github.com/ropensci/webservices/pull/425/files are essentially included in the dev version here, so closing

**Comment by nealrichardson** [comment]
Yeah they're essentially in master here on GitHub, just that's not on CRAN.
