### ISSUE TITLE
Would you please list RCloud on R Web Resource page?

### ISSUE THREAD

**Issue by calycolor** [ropensci/webservices#447]
Hello - would you please consider listing the open-source cloud-based notebook IDE, RCloud, on the CRAN Task View: Web Technologies and Services page?
https://urldefense.proofpoint.com/v2/url?u=https-3A__cran.r-2Dproject.org_web_views_WebTechnologies.html&d=DwIFaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=M97WDZ4xnnwS4fOabubAICx_T3Ul77c93YITaLw08P0&m=qhiFlwn_qtP4oNlWt6ce1Is4A9Dg6WGlqxfpkiZ5CPo&s=aKuuPMsvth9lkSBCSor9LOmVU05T4lf_AeXKpA3cddU&e=

RCloud is open-sourced under the MIT license https://github.com/att/rcloud - R and the R community would benefit from knowledge of a open-source IDE that is similar to but has more functionality than other notebook environments like Jupyter.

**Comment by sckott** [comment]
thanks @calycolor will have a look and see if it fits
