### ISSUE TITLE
Splashr

### ISSUE THREAD

**Issue by KnutJaegersberg** [ropensci/webservices#453]
Render javascript service 

https://github.com/hrbrmstr/splashr

**Comment by KnutJaegersberg** [comment]
Also you can easily render javascript via a tor based splash instance for ip shuffelling during scraping

https://github.com/TeamHG-Memex/aquarium

**Comment by sckott** [comment]
thanks, I'll add `splashr` - probably won't add aquarium since we only talk about R pkgs here
