### ISSUE TITLE
New Azure packages

### ISSUE THREAD

**Issue by Hong-Revo** [ropensci/webservices#458]
Hi, I've written a number of packages for talking to Microsoft's Azure cloud from R. It would be good to get them listed on the task view.

- [AzureRMR](https://cran.r-project.org/package=AzureRMR): interface to Resource Manager. Manage resource groups, create and delete and resources, deploy and delete templates.
- [AzureVM](https://cran.r-project.org/package=AzureVM): interface to virtual machines. Includes a number of templates for deploying Azure Data Science VMs, which are preloaded with several packages relevant to statistics and machine learning.
- [AzureStor](https://cran.r-project.org/package=AzureStor): interface to Azure Storage accounts. Provides facilities for efficient file transfers, managing storage, and an interface to the AzCopy commandline utility.
- [AzureContainers](https://cran.r-project.org/package=AzureContainers): containers in Azure (ACI, ACR and AKS). Deploy and delete Docker repositories and Kubernetes clusters; manage containers and images; deploy Kubernetes services.

**Comment by sckott** [comment]
sure, can you add a section under 

Web Services -> Cloud Computing and Storage -> Azure Web Services:

**Comment by Hong-Revo** [comment]
Hi, just wondering when this will show up in the task view? I went to cloud.r-project.org just now, and it's still displaying the old version.

**Comment by sckott** [comment]
soon. prob. tomorrow

**Comment by Hong-Revo** [comment]
Not sure why, but the CRAN page still hasn't been updated... for example, the README.md file on this repo lists AzureAuth as one of the packages under "Authentication", but it's missing in the CRAN version.

**Comment by sckott** [comment]
i've submitted it but it's not in my control if it gets accepted
