### ISSUE TITLE
Add zen4R package (R Interface to Zenodo API)

### ISSUE THREAD

**Issue by eblondel** [ropensci/webservices#461]
Would it be possible to add [zen4R](https://doi.org/10.5281/zenodo.2547036) package to the webservices task view? I believe this could fit well in paragraph ``Reference/bibliography/citation management``.

Some info about the package:

* zen4R provides an Interface to 'Zenodo' (<https://zenodo.org>) REST API, including management of depositions, attribution of DOIs by 'Zenodo' and upload of files.
* Project page: https://github.com/eblondel/zen4R
* CRAN page: https://cran.r-project.org/package=zen4R
* Current version: 0.2 (published today 2019-08-02)

Thanks in advance

**Comment by sckott** [comment]
Sounds good, can you send a PR?

**Comment by eblondel** [comment]
https://github.com/ropensci/webservices/pull/462
