### ISSUE TITLE
Information on connecting to SOAP are outdated

### ISSUE THREAD

**Issue by Patrikios** [ropensci/webservices#466]
I think the package SSOAP should be removed from task view as it is not anymore available on cran and the relative S´s R repository @omegahat is not doing the trick neither. Hence not usable. R needs something like zeep module in Python to keep it alive.

**Comment by sckott** [comment]
thanks @Patrikios - since it is the only SOAP client I know of for R, i think we should keep the mention of it, but we can change it to warn potential users that it may not work. thoughts?

**Comment by Patrikios** [comment]
The package might work when manually installed on pre 3.5 generation of R I suppose (not tested). Other than that I read rcurl package might be useful for soap web services queries.

**Comment by sckott** [comment]
i'll edit the text soon
