### ISSUE TITLE
add beakr

### ISSUE THREAD

**Issue by sckott** [ropensci/webservices#468]
https://cran.r-project.org/web/packages/beakr/index.html 
https://github.com/MazamaScience/beakr

from the author (adapt for the task view)

> beakr is a rewrite of the now archived jug package, and provides an R version of functionality found in python Flask and javascript Express.js. It uses R6 classes and wraps basic functionality provided by httpuv.

**Comment by pachadotdev** [comment]
added in #30a65f9
